---
- name: Configure openhrc router
  hosts: router
  gather_facts: false
  roles:
    - role: base
      tags: [base]
    - role: update
      tags: [update]
    - role: network
      tags: [network]
    - role: badhost
      tags: [badhost]
    - role: firewall
      tags: [firewall]
    - role: adblock
      tags: [adblock]
    - role: dns
      tags: [dns]
    - role: dhcp
      tags: [dhcp]
    - role: ntp
      tags: [ntp]
    - role: upnp
      tags: [upnp]
    - role: ddns
      tags: [ddns]
